# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da329fdc73425564eaa76c92af8d1a6113e56a5a362c02120b3b14dd828e1728266a2402b920aec422d645869e671c4cb5e39abdb9da36c14654d9db82568ec5

test:
  secret_key_base: c80c3fac2d535185a14b53d854d5d7b643333831761677fd0e5b149728462c1c8ed52b1b576d9757f187ce59cdfe25c56e94ab657aa645665e7b352e18c436cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
